routes/web.php
<?php

use App\Http\Controllers\ActivityController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\DeliveryController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});



Route::get('ajax-deliveries', [DeliveryController::class,'ajaxIndex']);
Route::post('ajax-deliveries/{delivery}',[DeliveryController::class,'ajaxDestroy']);

Route::get('ajax-products', [ProductController::class,'ajaxIndex']);
Route::post('ajax-product/{product}',[ProductController::class,'ajaxDestroy']);


Route::get('activity-log', ActivityController::class)->name('activityLog');
Route::put('deliveries/emei/{delivery}',[DeliveryController::class,'addImei'])->name('deliveries.products.imeis');
Route::delete('deliveries/clear/{delivery}',[DeliveryController::class,'clearProducts'])->name('deliveries.products.clear');
Route::get('deliveries/pdf/{delivery}',[DeliveryController::class,'generatePDF'])->name('deliveries.generatePDF');
Route::resource('deliveries',DeliveryController::class);
Route::resource('products',ProductController::class);


Route::get('users', [UserController::class,'index']);               //test
Route::post('delete/{id}', [UserController::class, 'destroy']);     //test

app/Models/Delivery.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;

class Delivery extends Model
{
    use HasFactory,LogsActivity;

    protected static $logAttributes = ['total', 'is_pending'];

    public function getDescriptionForEvent(string $eventName): string
    {
        return "Delivery has been {$eventName}";
    }

    protected static $logOnlyDirty = true;

    protected $guarded = [];


    public function products()
    {
        return $this->belongsToMany(Product::class)->withPivot('qty');
    }


    public function total()
    {
        return $this->products->sum(function ($product) {
            return $product['price']*$product->pivot->qty;
        });
    }



    public function imeis()
    {
        return $this->hasManyThrough(Imei::class,Product::class,'id');
        // return $this->hasManyThrough(Imei::class,DeliveryProduct::class);
    }




}

app/Http/Controllers/DeliveryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Imei;
use App\Models\Product;
use App\Models\Delivery;
use App\Http\Requests\Delivery\DeliveryUpdateRequest;
use App\Http\Requests\Delivery\DeliveryAddEmeiRequest;
use Illuminate\Support\Facades\DB;
use PDF;
use Spatie\Activitylog\Models\Activity;

class DeliveryController extends Controller
{

    public function index()
    {
        $deliveries = Delivery::all();
        return view('deliveries.index', compact('deliveries'));
    }

    public function create()
    {
        return view('deliveries.create');
    }

    public function edit(Delivery $delivery)
    {
        $products = Product::all();
        $imeis = Imei::all();               
        return view('deliveries.edit', compact(['delivery', 'products','imeis']));
    }

    public function store()
    {
        $delivery = new Delivery();
        $delivery->save();

        return back()->with("message", 'New Delivery Order Created');
    }

    public function update(DeliveryUpdateRequest $request, Delivery $delivery)
    {
        $products = $request->all()['products'];
        $qty = $request->all()['qty'];

        foreach ($products as $productId) {
            $delivery->products()->attach(Product::find($productId), ['qty' => $qty]);
        }

        return back()->with("message", sizeof($products) > 1 ? 'Products Added' : 'Product Added');
    }

    public function clearProducts(Delivery $delivery)
    {
        $ids = $delivery->products->pluck('id');

        $delivery->products()->detach($ids);

        return back()->with('message','Cart Cleared');
    }


    public function addImei(DeliveryAddEmeiRequest $request, Delivery $delivery)
    {
       
        $imeis = $request->all()['imei'];

        foreach ($imeis as $pair) {
            foreach ($pair as $productName => $imei) {
                
                $productId = Product::where('name',$productName)->pluck('id')[0];
                
                Imei::create([
                    'imeis' => $imei,
                    'product_id' => $productId,
                    ]);
                }
            }
            

        // change delivery status
        $delivery->is_pending = false;
        $delivery->total = $delivery->total();
        $delivery->save();
        
        return redirect()->route('deliveries.index')->with('message', sizeof($imeis)>1? 'Imeis Added And Delivery Completed' : 'Imei Added And Delivery Completed');
    }


    public function destroy(Delivery $delivery)
    {
        Delivery::destroy($delivery->id);

        return back()->with('message', 'Delivery Deleted');
    }

    public function generatePDF(Delivery $delivery)
    {  
        return PDF::loadView('PDFs.delivery', ['delivery' => $delivery])->stream();
    }





    public function ajaxIndex()
    {
        $deliveries = Delivery::latest()->get();
        return view('deliveries.ajax-index',['deliveries' => $deliveries]);
    }

    public function ajaxDestroy(Delivery $delivery)
    {

        $delete = $delivery->delete();

        // check data deleted or not
        if ($delete == 1) {
            $success = true;
            $message = "Delivery deleted successfully";
        } else {
            $success = true;
            $message = "Delivery not found";
        }

        //  Return response
        return response()->json([
            'success' => $success,
            'message' => $message,
        ]);

    }


}

resources/views/deliveries/ajax-index.blade.php
@extends('layout')

@section('content')

@push('scripts')
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@10"></script>
@endpush
    

<table class="table">
    <thead>
      <tr>
          <th scope="col">Delivery #</th>
          <th scope="col">Date</th>
          <th scope="col">Status</th>
          <th scope="col">Edit</th>
          <th scope="col">Delete</th>
      </tr>
    </thead>

    <tbody>
     
      @foreach ($deliveries as $key => $delivery)
        <tr id="{{ $delivery->id }}">
            <td>{{ ++$key}}</td>
            <td>{{ $delivery->created_at }}</td>
            @if ($delivery->is_pending)
                <td>Pending / Not Completed</td>
            @else
                <td>Completed</td>
            @endif

            @if (!$delivery->is_pending)
            
            @else

            @endif
            <td>
              @if (!$delivery->is_pending)
                <button><a href="{{ route('deliveries.generatePDF',$delivery->id) }}">PDF</a></button>
              @else
                <button><a href="{{ route('deliveries.edit',$delivery->id) }}">EDIT</a></button>
              @endif
            </td>
            <td>
              <button class="btn btn-danger" onclick="deleteConfirmation({{$delivery->id}})">Delete</button>
          </td>
        </tr>    
      @endforeach
      
    </tbody>
  </table>


  {{-- <script src="{{ asset("/js/deliveries/delete.js") }}"></script> --}}
  <script>

    function deleteConfirmation(id) {
        swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then(function (e) {
            
            if (e.value === true) {
                var CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');
                
                $.ajax({
                    type: 'POST',
                    url: "{{url('/ajax-deliveries')}}/" + id,
                    data: {_token: CSRF_TOKEN},
                    dataType: 'JSON',
                    success:function (results){
                    if (results) {
                        Swal.fire(
                        'Deleted!',
                        'Your delivery has been deleted.',
                        'success'
                        )
                        $("tr").remove("#"+id)
                        }
                    }
                });

            } else {
                e.dismiss;
            }

        }, function (dismiss) {
            return false;
        })
    }
  </script>

@endsection

resources/views/deliveries/create.blade.php
@extends('layout')

@section('content')

    <h1>Crate delivery</h1>

    @if(Session::has('message'))
    <p class="alert alert-info">{{ Session::get('message') }}</p>
    @endif

    <form action="{{ route('deliveries.store') }}" method="POST">
        @csrf
        <button type="submit">Create a new one</button>
    </form>
    
@endsection

resources/views/deliveries/edit.blade.php
@extends('layout')

@section('content')


    
    <h2>Edit Delivery</h2>

    @if(Session::has('message'))
    <p class="alert alert-info">{{ Session::get('message') }}</p>
    @endif

    @foreach ($errors->all() as $message)
    <p class="alert alert-danger">{{ $message }}</p>
    @endforeach


    <div class="row row-list">
    
        

        <form method="POST" class="col-xs-3" action="{{ route('deliveries.update',$delivery) }}">
            @csrf
            @method('PUT')
            <select name="products[]" multiple>
                @foreach ($products as $product)
                    <option value="{{ $product->id }}">{{ $product->name }}</option>
                @endforeach
            </select> 
            
            <div>
                <p>Select quantity</p>
                <input name="qty" type="number">
            </div>
            <p>
                <button type="submit">Add to Order</button>
            </p>
        </form>
        
        <div class="col-xs-3 ">
            <p style="display: inline-block">Current Status is </p>

            @if ($delivery->is_pending)
                <span>pending!</span>
            @else
                <span>completed!</span>
            @endif

            @if (count($delivery->products))
            <h3>Currently Added Products</h3>
            
            <form action="{{ route('deliveries.products.clear',$delivery->id) }}" method="POST">
                @csrf
                @method('DELETE')
                @forelse ($delivery->products as $prod)
                    <p>{{$prod->name}} - {{ $prod->pivot->qty}} </p> 
                @empty
                    <p>Empty so far!</p>
                @endforelse

                <button type="submit">CLEAR PRODUCTS BASKET</button>
            </form>
            @endif
           
        </div>
    
        @if (count($delivery->products))
        <div class="col-xs-3 ">
            <h3>Add EMEIS</h3>
            <form action="{{ route('deliveries.products.imeis',$delivery) }}" method="POST">
                @csrf
                @method('PUT')
                @forelse ($delivery->products as $prod)

                <p>Product {{ $prod->name }}: {{ $prod->pivot->qty }} </p>
                
                <ul>
                    @for ($i = 0; $i < $prod->pivot->qty; $i++)
                    <li><input type="text" name="imei[][{{$prod->name}}]" placeholder="Enter IMEI"></li> 
                    <!-- <li><input type="text" name="{{$prod->name}}[]" placeholder="Enter IMEI"></li>   -->
                    @endfor
                </ul>
                @empty
                @endforelse

                <button type="submit">Add and Complete Delilvery</button>
            </form>
        </div>
        @endif
       
    </div>
@endsection

resources/views/deliveries/index.blade.php
@extends('layout')


@section('content')



@if(Session::has('message'))
<p class="alert alert-info">{{ Session::get('message') }}</p>
@endif

<form action="{{ route('deliveries.store') }}" method="POST">
  @csrf
  <button type="submit">Create New Delivery</button>
</form>
{{-- <a href="{{ route('deliveries.create') }}">Create New Delivery</a> --}}

<table class="table">
    <thead>
      <tr>
          <th scope="col">Delivery #</th>
          <th scope="col">Date</th>
          <th scope="col">Status</th>
          <th scope="col">Edit</th>
          <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
     
      @foreach ($deliveries as $key => $delivery)
        <tr>
            <td>{{ ++$key}}</td>
            <td>{{ $delivery->created_at }}</td>
            @if ($delivery->is_pending)
                <td>Pending / Not Completed</td>
            @else
                <td>Completed</td>
            @endif

            @if (!$delivery->is_pending)
            
            @else

            @endif
            <td>
              @if (!$delivery->is_pending)
                <button><a href="{{ route('deliveries.generatePDF',$delivery->id) }}">PDF</a></button>
              @else
                <button><a href="{{ route('deliveries.edit',$delivery->id) }}">EDIT</a></button>
              @endif
            </td>
            <td>
              <form action="{{ route('deliveries.destroy',$delivery->id) }}" method="POST">
                @csrf
                @method('delete')
                <button type="sumbmit">DELETE</button>
              </form>
          </td>
        </tr>    
      @endforeach
      
    </tbody>
  </table>


@endsection