routes/web.php
<?php

use App\Http\Controllers\ActivityController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\DeliveryController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});



Route::get('ajax-deliveries', [DeliveryController::class,'ajaxIndex']);
Route::post('ajax-deliveries/{delivery}',[DeliveryController::class,'ajaxDestroy']);

Route::get('ajax-products', [ProductController::class,'ajaxIndex']);
Route::post('ajax-product/{product}',[ProductController::class,'ajaxDestroy']);


Route::get('activity-log', ActivityController::class)->name('activityLog');
Route::put('deliveries/emei/{delivery}',[DeliveryController::class,'addImei'])->name('deliveries.products.imeis');
Route::delete('deliveries/clear/{delivery}',[DeliveryController::class,'clearProducts'])->name('deliveries.products.clear');
Route::get('deliveries/pdf/{delivery}',[DeliveryController::class,'generatePDF'])->name('deliveries.generatePDF');
Route::resource('deliveries',DeliveryController::class);
Route::resource('products',ProductController::class);


Route::get('users', [UserController::class,'index']);               //test
Route::post('delete/{id}', [UserController::class, 'destroy']);     //test

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;

class Product extends Model
{
    use HasFactory, LogsActivity;

    protected static $logAttributes = ['name', 'price'];

    public function getDescriptionForEvent(string $eventName): string
    {
        return "Product has been {$eventName}";
    }
    
    protected static $logOnlyDirty = true;
    
    protected $guarded = [];

    public function deliveries()
    {
        return $this->belongsToMany(Delivery::class)->withPivot('qty');
    }

    public function allImeis()
    {
        return $this->hasMany(Imei::class);
    }




    public function totalQuantity()
    {
        return count($this->allImeis);
    }

    public function totalSum()
    {
        return $this->totalQuantity()*$this->price;
    }

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Product\StoreProductRequest;
use App\Http\Requests\Product\UpdateProductRequest;
use App\Models\Product;
use Exception;
use Illuminate\Http\Request;

class ProductController extends Controller
{

    public function index()
    {
        $products = Product::all();

        return view('products.index',compact('products'));
    }

    public function show(Product $product)
    {
        return view('products.show',compact('product'));
    }


    public function create()
    {
        return view('products.create');
    } 



    public function store(StoreProductRequest $request)
    {

        $validated = $request->validated();

        Product::create([
            'name' => $validated['name'],
            'price' => $validated['price'], 
        ]);

        return back()->with('message','product added successuly');

    }

    public function edit(Product $product)
    {
        return view('products.edit',compact('product'));
    }

    public function update(UpdateProductRequest $request, Product $product)
    {
        
        $params = $request->validated();

        $product->name = $params['name'];
        $product->price = $params['price'];
        $product->update();


        return redirect()->route('products.show',$product)->with('message','edit successful');
    }

    public function destroy(Product $product)
    {
         $product->delete();

         return redirect()->route('products.index')->with('message',' product successfuly deleted');

    }

    public function ajaxIndex()
    {
        $products = Product::latest()->get();
        return view('products.ajax-index', compact('products'));
    }

    public function ajaxDestroy(Product $product)
    {

        
        $delete = $product->delete();

        // check data deleted or not
        if ($delete == 1) {
            $success = true;
            $message = "Product deleted successfully";
        } else {
            $success = true;
            $message = "Product not found";
        }

        //  Return response
        return response()->json([
            'success' => $success,
            'message' => $message,
        ]);

    }

}

resources/views/products/ajax-index.blade.php
@extends('layout')

@section('content')

@push('scripts')
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    {{-- <script src="{{ asset("/js/app.js") }}" defer></script> --}}
@endpush
    


<h2>All Products</h2>

<p><a href="{{ route('products.create') }}">Create Product</a></p>


<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Product</th>
        <th scope="col">Price</th>
        <th scope="col">Quantity</th>
        <th scope="col">Edit</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
     
      @foreach ($products as $index => $product)
        <tr id="{{ $product->id }}">
            <th scope="row">{{ ++$index }}</th>
            <td>{{ strtoupper($product->name) }}</td>
            <td>${{ $product->price }}</td>
            <th>{{ $product->totalQuantity()}}</th>
            <td>
                <form method="get" action="{{ route('products.edit',$product->id) }}">
                    <button type="submit">EDIT</button>
                </form>
            </td>
            <td>
                <button class="btn btn-danger" onclick="deleteConfirmation({{$product->id}})">Delete</button>
            </td>
        </tr>      
      @endforeach
      
    </tbody>
  </table>


    {{-- <script src="{{ asset("/js/products/delete.js") }}"></script> --}}
    <script>
        function deleteConfirmation(id) {
            swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then(function (e) {
                
                if (e.value === true) {
                    var CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');
                    
                    $.ajax({
                        type: 'POST',
                        url: "{{url('/ajax-product')}}/" + id,
                        data: {_token: CSRF_TOKEN},
                        dataType: 'JSON',
                        success:function (results){
                        if (results) {
                            Swal.fire(
                            'Deleted!',
                            'Your prodcut has been deleted.',
                            'success'
                            )
                            $( "tr" ).remove( "#"+id );
                            }
                        }
                    });
                } else {
                    e.dismiss;
                }

            }, function (dismiss) {
                return false;
            })
        }
    </script>

@endsection

resources/views/products/create.blade.php
@extends('layout')

@section('content')    

    @if(Session::has('message'))
    <p class="alert alert-info">{{ Session::get('message') }}</p>
    @endif

    <h1>Create product</h1>
    <form action="{{ route('products.store') }}" method="POST">
        @csrf
        <p>Product Name</p>
        <input type="text" name="name" >
        <p>Price</p>
        <input type="number" name="price">
        <p>
            <button type="submit">Create</button>
        </p>
    </form>

@endsection

resources/views/products/edit.blade.php
@extends('layout')


@section('content')


    @foreach ($errors->all() as $message)
        <p>{{ $message }}</p>
    @endforeach

    <h2>Edit Product</h2>

    <form method="POST" action="{{ route('products.update',$product->id) }}">
        @csrf
        @method('put')

        <p>Name</p>
        <input type="text" name="name" value="{{ $product->name }}">
        <p>Price</p>
        <input type="number"name="price" value="{{ $product->price }}">

        <p>
            <button type="submit">Edit</button>
        </p>
    </form>


@endsection

resources/views/products/index.blade.php
@extends('layout')


@section('content')

    @if(Session::has('message'))
        <p class="alert alert-info">{{ Session::get('message') }}</p>
    @endif


    <h2>All Products</h2>

    <p><a href="{{ route('products.create') }}">Create Product</a></p>


    <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Product</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
          </tr>
        </thead>
        <tbody>
         
          @foreach ($products as $index => $product)
            <tr>
                <th scope="row">{{ ++$index }}</th>
                <td>{{ strtoupper($product->name) }}</td>
                <td>${{ $product->price }}</td>
                <th>{{ $product->totalQuantity()}}</th>
                <td>
                    <form method="get" action="{{ route('products.edit',$product->id) }}">
                        <button type="submit">EDIT</button>
                    </form>
                </td>
                <td>
                    <form method="POST" action="{{ route('products.destroy',$product->id) }}">
                        @csrf
                        @method('delete')

                        <button type="submit">Delete</button>

                    </form>
                </td>
            </tr>      
          @endforeach
          
        </tbody>
      </table>

   
@endsection

resources/views/products/show.blade.php
@extends('layout')

@section('content')

@if(Session::has('message'))
<p class="alert alert-success">{{ Session::get('message') }}</p>
@endif

<h2>Product Details</h2>

<p>Product</p>
<h3>{{$product->name }}</h3>

<p>Price</p>
<h3>{{$product->price }}</h3>

@endsection